# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools/android/emulator/emulator_meta_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tools/android/emulator/emulator_meta_data.proto',
  package='tools.android.emulator',
  serialized_pb='\n/tools/android/emulator/emulator_meta_data.proto\x12\x16tools.android.emulator\"\xcc\x06\n\x12\x45mulatorMetaDataPb\x12\x11\n\tmemory_mb\x18\x01 \x01(\x03\x12\x0c\n\x04skin\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65nsity\x18\x03 \x01(\x03\x12\x10\n\x08\x61pi_name\x18\x04 \x01(\t\x12\x0f\n\x07vm_heap\x18\x05 \x01(\x03\x12\x18\n\x10system_image_dir\x18\x06 \x01(\t\x12\x39\n\rboot_property\x18\x07 \x03(\x0b\x32\".tools.android.emulator.PropertyPb\x12\x10\n\x08qemu_arg\x18\x08 \x03(\t\x12\x1f\n\x17unused_emulator_version\x18\t \x01(\t\x12\x10\n\x08net_type\x18\n \x01(\t\x12\x11\n\tnet_delay\x18\x0b \x01(\t\x12\x11\n\tnet_speed\x18\x0c \x01(\t\x12\x1d\n\x15\x65mulator_architecture\x18\r \x01(\t\x12\x1e\n\x16unused_local_execution\x18\x0e \x01(\x08\x12\x14\n\x0cwith_display\x18\x0f \x01(\x08\x12<\n\tperf_data\x18\x10 \x03(\x0b\x32).tools.android.emulator.PerformanceDataPb\x12\x16\n\x0esdcard_size_mb\x18\x11 \x01(\x05\x12\x10\n\x08with_kvm\x18\x12 \x01(\x08\x12?\n\x13\x61vd_config_property\x18\x13 \x03(\x0b\x32\".tools.android.emulator.PropertyPb\x12\x16\n\x0ewith_adbd_pipe\x18\x14 \x01(\x08\x12\x19\n\x11with_patched_adbd\x18\x15 \x01(\x08\x12\x14\n\x0csupports_gpu\x18\x16 \x01(\x08\x12!\n\x19supported_open_gl_drivers\x18\x17 \x03(\t\x12\x1e\n\x16sensitive_system_image\x18\x18 \x01(\x08\x12N\n\remulator_type\x18\x19 \x01(\x0e\x32\x37.tools.android.emulator.EmulatorMetaDataPb.EmulatorType\x12\x19\n\x11system_image_path\x18\x1a \x01(\t\",\n\x0c\x45mulatorType\x12\x08\n\x04QEMU\x10\x00\x12\x07\n\x03UMA\x10\x01\x12\t\n\x05QEMU2\x10\x02\")\n\nPropertyPb\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"[\n\x11PerformanceDataPb\x12\x15\n\ractivity_name\x18\x01 \x01(\t\x12/\n\x06timing\x18\x02 \x03(\x0b\x32\x1f.tools.android.emulator.TimerPb\"K\n\x07TimerPb\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10number_of_starts\x18\x02 \x01(\x05\x12\x18\n\x10\x61\x63\x63umulated_time\x18\x03 \x01(\x03')



_EMULATORMETADATAPB_EMULATORTYPE = _descriptor.EnumDescriptor(
  name='EmulatorType',
  full_name='tools.android.emulator.EmulatorMetaDataPb.EmulatorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QEMU', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UMA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QEMU2', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=876,
  serialized_end=920,
)


_EMULATORMETADATAPB = _descriptor.Descriptor(
  name='EmulatorMetaDataPb',
  full_name='tools.android.emulator.EmulatorMetaDataPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='memory_mb', full_name='tools.android.emulator.EmulatorMetaDataPb.memory_mb', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skin', full_name='tools.android.emulator.EmulatorMetaDataPb.skin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='density', full_name='tools.android.emulator.EmulatorMetaDataPb.density', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='api_name', full_name='tools.android.emulator.EmulatorMetaDataPb.api_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vm_heap', full_name='tools.android.emulator.EmulatorMetaDataPb.vm_heap', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_image_dir', full_name='tools.android.emulator.EmulatorMetaDataPb.system_image_dir', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boot_property', full_name='tools.android.emulator.EmulatorMetaDataPb.boot_property', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qemu_arg', full_name='tools.android.emulator.EmulatorMetaDataPb.qemu_arg', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unused_emulator_version', full_name='tools.android.emulator.EmulatorMetaDataPb.unused_emulator_version', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net_type', full_name='tools.android.emulator.EmulatorMetaDataPb.net_type', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net_delay', full_name='tools.android.emulator.EmulatorMetaDataPb.net_delay', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net_speed', full_name='tools.android.emulator.EmulatorMetaDataPb.net_speed', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emulator_architecture', full_name='tools.android.emulator.EmulatorMetaDataPb.emulator_architecture', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unused_local_execution', full_name='tools.android.emulator.EmulatorMetaDataPb.unused_local_execution', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='with_display', full_name='tools.android.emulator.EmulatorMetaDataPb.with_display', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='perf_data', full_name='tools.android.emulator.EmulatorMetaDataPb.perf_data', index=15,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdcard_size_mb', full_name='tools.android.emulator.EmulatorMetaDataPb.sdcard_size_mb', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='with_kvm', full_name='tools.android.emulator.EmulatorMetaDataPb.with_kvm', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avd_config_property', full_name='tools.android.emulator.EmulatorMetaDataPb.avd_config_property', index=18,
      number=19, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='with_adbd_pipe', full_name='tools.android.emulator.EmulatorMetaDataPb.with_adbd_pipe', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='with_patched_adbd', full_name='tools.android.emulator.EmulatorMetaDataPb.with_patched_adbd', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supports_gpu', full_name='tools.android.emulator.EmulatorMetaDataPb.supports_gpu', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='supported_open_gl_drivers', full_name='tools.android.emulator.EmulatorMetaDataPb.supported_open_gl_drivers', index=22,
      number=23, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensitive_system_image', full_name='tools.android.emulator.EmulatorMetaDataPb.sensitive_system_image', index=23,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='emulator_type', full_name='tools.android.emulator.EmulatorMetaDataPb.emulator_type', index=24,
      number=25, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_image_path', full_name='tools.android.emulator.EmulatorMetaDataPb.system_image_path', index=25,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EMULATORMETADATAPB_EMULATORTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=920,
)


_PROPERTYPB = _descriptor.Descriptor(
  name='PropertyPb',
  full_name='tools.android.emulator.PropertyPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tools.android.emulator.PropertyPb.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tools.android.emulator.PropertyPb.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=922,
  serialized_end=963,
)


_PERFORMANCEDATAPB = _descriptor.Descriptor(
  name='PerformanceDataPb',
  full_name='tools.android.emulator.PerformanceDataPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activity_name', full_name='tools.android.emulator.PerformanceDataPb.activity_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timing', full_name='tools.android.emulator.PerformanceDataPb.timing', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=965,
  serialized_end=1056,
)


_TIMERPB = _descriptor.Descriptor(
  name='TimerPb',
  full_name='tools.android.emulator.TimerPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tools.android.emulator.TimerPb.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_starts', full_name='tools.android.emulator.TimerPb.number_of_starts', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accumulated_time', full_name='tools.android.emulator.TimerPb.accumulated_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1058,
  serialized_end=1133,
)

_EMULATORMETADATAPB.fields_by_name['boot_property'].message_type = _PROPERTYPB
_EMULATORMETADATAPB.fields_by_name['perf_data'].message_type = _PERFORMANCEDATAPB
_EMULATORMETADATAPB.fields_by_name['avd_config_property'].message_type = _PROPERTYPB
_EMULATORMETADATAPB.fields_by_name['emulator_type'].enum_type = _EMULATORMETADATAPB_EMULATORTYPE
_EMULATORMETADATAPB_EMULATORTYPE.containing_type = _EMULATORMETADATAPB;
_PERFORMANCEDATAPB.fields_by_name['timing'].message_type = _TIMERPB
DESCRIPTOR.message_types_by_name['EmulatorMetaDataPb'] = _EMULATORMETADATAPB
DESCRIPTOR.message_types_by_name['PropertyPb'] = _PROPERTYPB
DESCRIPTOR.message_types_by_name['PerformanceDataPb'] = _PERFORMANCEDATAPB
DESCRIPTOR.message_types_by_name['TimerPb'] = _TIMERPB

class EmulatorMetaDataPb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMULATORMETADATAPB

  # @@protoc_insertion_point(class_scope:tools.android.emulator.EmulatorMetaDataPb)

class PropertyPb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPERTYPB

  # @@protoc_insertion_point(class_scope:tools.android.emulator.PropertyPb)

class PerformanceDataPb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERFORMANCEDATAPB

  # @@protoc_insertion_point(class_scope:tools.android.emulator.PerformanceDataPb)

class TimerPb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMERPB

  # @@protoc_insertion_point(class_scope:tools.android.emulator.TimerPb)


# @@protoc_insertion_point(module_scope)
