# Publicly visible androidx.ext.junit Kotlin extension library

package(
    default_applicable_licenses = ["//:license"],
    default_testonly = 1,
)

licenses(["notice"])

alias(
    name = "junit",
    actual = "//ktx/ext/junit/java/androidx/test/ext/junit",
    visibility = ["//visibility:public"],
)
