# Publicly visible androidx.ext.junit Kotlin extension library

package(default_applicable_licenses = ["//:license"])

licenses(["notice"])

alias(
    name = "junit",
    testonly = 1,
    actual = "//ktx/ext/junit/java/androidx/test/ext/junit",
    visibility = ["//visibility:public"],
)
