# Description:
#   Sample UI tests.

load("//build_extensions:android_app_instrumentation_tests.bzl", "android_app_instrumentation_tests")
load("//build_extensions:android_library_test.bzl", "axt_android_library_test")
