steps:
# build the docker image that contains bazel + android SDK        
- name: gcr.io/cloud-builders/docker
  args: ['build', '--tag=gcr.io/$PROJECT_ID/bazel-android', '.']
# build the bazel targets using above docker image  
- name: gcr.io/$PROJECT_ID/bazel-android
  args: ['build', '//core']
timeout: '1200s'
