"""Defines currently released stable AXT versions."""

# currently only used for documentation purposes

RUNNER_VERSION = "1.6.1"
RULES_VERSION = "1.6.1"
MONITOR_VERSION = "1.7.1"
ESPRESSO_VERSION = "3.6.1"
CORE_VERSION = "1.6.1"
ESPRESSO_DEVICE_VERSION = "1.0.1"
ANDROIDX_JUNIT_VERSION = "1.2.1"
ANDROIDX_TRUTH_VERSION = "1.6.0"
ANNOTATION_VERSION = "1.0.1"
ORCHESTRATOR_VERSION = "1.5.0"
SERVICES_VERSION = "1.5.0"
