"""Defines currently released stable AXT versions."""

# currently only used for documentation purposes

RUNNER_VERSION = "1.5.1"
RULES_VERSION = "1.5.0"
MONITOR_VERSION = "1.6.0"
ESPRESSO_VERSION = "3.5.0"
CORE_VERSION = "1.5.0"
ESPRESSO_DEVICE_VERSION = "NA"
ANDROIDX_JUNIT_VERSION = "1.1.4"
ANDROIDX_TRUTH_VERSION = "1.5.0"
ANNOTATION_VERSION = "1.0.1"
ORCHESTRATOR_VERSION = "1.4.2"
SERVICES_VERSION = "1.4.2"
