"""Defines current AXT versions and dependencies.

Ensure UsageTrackerRegistry is updated accordingly when incrementing version numbers.
"""

# AXT versions
RUNNER_VERSION = "1.3.1-SNAPSHOT"
ESPRESSO_VERSION = "3.3.1-SNAPSHOT"
CORE_VERSION = "1.3.1-SNAPSHOT"
ANDROIDX_JUNIT_VERSION = "1.1.3-SNAPSHOT"
ANDROIDX_TRUTH_VERSION = "1.3.1-SNAPSHOT"
UIAUTOMATOR_VERSION = "2.2.0"
JANK_VERSION = "1.0.1"
SERVICES_VERSION = RUNNER_VERSION

# Maven dependency versions
ANDROIDX_VERSION = "1.0.0"
ANDROIDX_VERSION_PATH = "1.0.0"
GOOGLE_MATERIAL_VERSION = "1.0.0"
ANDROIDX_LIFECYCLE_VERSION = "2.0.0"
ANDROIDX_MULTIDEX_VERSION = "2.0.0"

JUNIT_VERSION = "4.12"
HAMCREST_VERSION = "1.3"
TRUTH_VERSION = "1.0"
GUAVA_VERSION = "27.0.1-android"
