"""Defines current AXT versions and dependencies.

Ensure UsageTrackerRegistry is updated accordingly when incrementing version numbers.
"""

# AXT versions
RUNNER_VERSION = "1.4.1-alpha03"  # stable 1.4.0
RULES_VERSION = "1.4.1-alpha03"  # stable 1.4.0
MONITOR_VERSION = "1.5.0"  # stable 1.5.0
ESPRESSO_VERSION = "3.5.0-alpha03"  # stable 3.4.0
CORE_VERSION = "1.4.1-alpha03"  # stable 1.4.0
ANDROIDX_JUNIT_VERSION = "1.1.4-alpha03"  # stable 1.1.3
ANDROIDX_TRUTH_VERSION = "1.5.0-alpha03"  # stable 1.4.0
UIAUTOMATOR_VERSION = "2.2.0"
JANK_VERSION = "1.0.1"
SERVICES_VERSION = "1.4.1"  # stable 1.4.1
ORCHESTRATOR_VERSION = "1.4.1"  # stable 1.4.1
ANNOTATION_VERSION = "1.0.0"  # stable 1.0.0

# Maven dependency versions
ANDROIDX_ANNOTATION_VERSION = "1.2.0"
ANDROIDX_ANNOTATION_EXPERIMENTAL_VERSION = "1.1.0"
ANDROIDX_COMPAT_VERSION = "1.3.1"
ANDROIDX_CONCURRENT_VERSION = "1.1.0"
ANDROIDX_CORE_VERSION = "1.6.0"
ANDROIDX_FRAGMENT_VERSION = "1.3.6"
ANDROIDX_CURSOR_ADAPTER_VERSION = "1.0.0"
ANDROIDX_DRAWER_LAYOUT_VERSION = "1.1.1"
ANDROIDX_LEGACY_SUPPORT_VERSION = "1.0.0"
ANDROIDX_LIFECYCLE_VERSION = "2.3.1"
ANDROIDX_MULTIDEX_VERSION = "2.0.0"
ANDROIDX_RECYCLERVIEW_VERSION = "1.2.1"
TRACING_VERSION = "1.0.0"
ANDROIDX_VIEWPAGER_VERSION = "1.0.0"
GOOGLE_MATERIAL_VERSION = "1.4.0"
KOTLIN_VERSION = "1.5.31"

# accessibilitytestframework
ATF_VERSION = "3.1.2"
JUNIT_VERSION = "4.13.2"
HAMCREST_VERSION = "1.3"
TRUTH_VERSION = "1.1.3"
GUAVA_VERSION = "30.1.1-android"
GUAVA_LISTENABLEFUTURE_VERSION = "1.0"
