load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

licenses(["notice"])

package(default_visibility = [
    "//visibility:public",
])

exports_files([
    "AndroidManifest_target_stub.xml",
    "AndroidManifest_instrumentation_test_template.xml",
    "AndroidManifest_robolectric.xml",
    "robolectric.properties",
    "mainDexClasses.rules",
])
