# Alias for androidx.test.espresso.core API library

package(
    default_applicable_licenses = ["//espresso:license"],
    default_testonly = 1,
)

licenses(["notice"])

alias(
    name = "core",
    actual = "//espresso/core/java/androidx/test/espresso",
    visibility = ["//visibility:public"],
)
