# Alias for androidx.test.espresso.core API library

package(default_applicable_licenses = ["//espresso:license"])

licenses(["notice"])

alias(
    name = "core",
    testonly = 1,
    actual = "//espresso/core/java/androidx/test/espresso",
    visibility = ["//visibility:public"],
)
