java_library(
    name = "jar1",
    srcs = ["Jar1Class.java"],
    visibility = [
        "//build_extensions/jar_combiner/javatests:__subpackages__",
    ],
)

java_library(
    name = "jar2",
    srcs = [
        "Jar2Class.java",
    ],
    visibility = [
        "//build_extensions/jar_combiner/javatests:__subpackages__",
    ],
)

java_library(
    name = "jar_with_r",
    srcs = [
        "Jar1Class.java",
        "R.java",
    ],
    visibility = [
        "//build_extensions/jar_combiner/javatests:__subpackages__",
    ],
)
