# # androidx.test ktx extensions

licenses(["notice"])

package(
    default_applicable_licenses = ["//:license"],
    default_testonly = 1,
    default_visibility = ["//:__subpackages__"],
)

exports_files([
    "LICENSE",
])
