# Copyright 2012 Google Inc. All Rights Reserved.
# Author: thomaswk@google.com (Thomas Knych)
#
# Description:
#   Please see the subpackages for android_device targets by brand name.

# For //devtools/bazel/integration:android_test_cc_test:
package(default_visibility = ["//devtools/bazel/integration:__subpackages__"])

exports_files(
    glob(["macro/*bzl"]),
)

filegroup(
    name = "build_macros",
    srcs = glob(["macro/*bzl"]),
)
