# Copyright 2012 Google Inc. All Rights Reserved.
# Author: thomaswk@google.com (Thomas Knych)
#
# Description:
#   Please see the subpackages for android_device targets by brand name.

exports_files(
    glob(["macro/*bzl"]),
)

filegroup(
    name = "build_macros",
    srcs = glob(["macro/*bzl"]),
)
