# Publicly visible alias to the runner target

package(default_applicable_licenses = ["//:license"])

licenses(["notice"])

alias(
    name = "android_junit_runner",
    actual = "//runner/android_junit_runner/java/androidx/test:runner",
    visibility = ["//visibility:public"],
)
