# Publicly visible junit extensions for Android

package(default_applicable_licenses = ["//:license"])

licenses(["notice"])

alias(
    name = "junit",
    testonly = 1,
    actual = "//ext/junit/java/androidx/test/ext/junit",
    visibility = ["//visibility:public"],
)
