# Publicly visible junit extensions for Android

package(
    default_applicable_licenses = ["//:license"],
    default_testonly = 1,
)

licenses(["notice"])

alias(
    name = "junit",
    actual = "//ext/junit/java/androidx/test/ext/junit",
    visibility = ["//visibility:public"],
)
