# Publicly visible androidx.test.core Kotlin extension library

package(default_applicable_licenses = ["//:license"])

licenses(["notice"])

alias(
    name = "core",
    testonly = 1,
    actual = "//ktx/core/java/androidx/test/core",
    visibility = ["//visibility:public"],
)
