# Publicly visible androidx.test.core Kotlin extension library

package(default_applicable_licenses = ["//:license"])

licenses(["notice"])

load("@build_bazel_rules_android//android:rules.bzl", "android_library")

android_library(
    name = "core",
    testonly = 1,
    visibility = ["//visibility:public"],
    exports = ["//ktx/core/java/androidx/test/core"],
)
