# Publicly visible androidx.test.core Kotlin extension library

package(
    default_applicable_licenses = ["//:license"],
    default_testonly = 1,
)

licenses(["notice"])

alias(
    name = "core",
    actual = "//ktx/core/java/androidx/test/core",
    visibility = ["//visibility:public"],
)
