# Alias for androidx.test.espresso.web API library

package(default_applicable_licenses = ["//espresso:license"])

licenses(["notice"])

alias(
    name = "web",
    testonly = 1,
    actual = "//espresso/web/java/androidx/test/espresso/web:espresso_web_aar_lib",
    visibility = ["//visibility:public"],
)
