# Alias for androidx.test.espresso.web API library

package(
    default_applicable_licenses = ["//espresso:license"],
    default_testonly = 1,
)

licenses(["notice"])

alias(
    name = "web",
    actual = "//espresso/web/java/androidx/test/espresso/web:espresso_web_aar_lib",
    visibility = ["//visibility:public"],
)
