# Alias for androidx.test.espresso.device API library

package(default_applicable_licenses = ["//espresso:license"])

licenses(["notice"])

alias(
    name = "device",
    testonly = 1,
    actual = "//espresso/device/java/androidx/test/espresso/device",
    visibility = ["//visibility:public"],
)
