# Alias for androidx.test.espresso.device API library

package(
    default_applicable_licenses = ["//espresso:license"],
    default_testonly = 1,
)

licenses(["notice"])

alias(
    name = "device",
    actual = "//espresso/device/java/androidx/test/espresso/device",
    visibility = ["//visibility:public"],
)
